name: Deploy Flask app to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to PythonAnywhere
        run: |
          pip install requests
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          api_token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          domain_name: ${{ secrets.PYTHONANYWHERE_DOMAIN }}
          curl -X POST -H "Authorization: Token ${api_token}" -F "content=@main.py" "https://www.pythonanywhere.com/api/v0/user/${username}/files/mysite/main.py"

      - name: Reload PythonAnywhere web app
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_DOMAIN }}/reload/
