name: Deploy to PythonAnywhere

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to PythonAnywhere
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          api_token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          domain_name: ${{ secrets.PYTHONANYWHERE_DOMAIN }}
      - name: Run application
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: python your_script.py
