name: Deploy to PythonAnywhere

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to PythonAnywhere
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
        with:
          host: 'www.pythonanywhere.com'
          username: 'trin'
          api_token: '5c5fa25e0ae441d2ece1637e08a1e4fce9ae3ebd'
          domain_name: 'https://trin.pythonanywhere.com/'
