# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy 
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build, Scan, and Deploy Python App to Azure Web App - secureCartTrees

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=.
          pytest --junitxml=results.xml

      # Optional: Add step to run tests here

      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-deps.sarif

      - name: Run Snyk Code to check for vulnerabilities in proprietary code
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk-code.sarif

      - name: Upload Snyk dependency scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-deps.sarif

      - name: Upload Snyk Code scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A5F77AE0907F43878D39716F87C4931A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_06ECAE42B989466999073FA53D6A96F2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4650C14B5DAC4BF4BD6CDFB2EE8D4F1F }}

  zap-scan:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Full Zap Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'securecarttrees-fyaebscfggfudpcp.uksouth-01.azurewebsites.net'
          fail_action: false
          artifact_name: zap_scan_report

      - name: Export Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path:
            zap_report/*.html
